### PR TITLE
added a debug_navbar to make development easier

### PR DESCRIPTION
**Pull request by gkarolyi**
Added a `views/shared/_debug_navbar` component, rendered in `layouts/application` to make it easier to navigate around while developing/debugging

### CODE REVIEW

**Review by coDecs27 — APPROVED** [review]
Good idea!

**Comment by hannvo** [comment]
hi. great! maybe we can delete the applicationsController part, because that will be in my commit?

**Comment by hannvo** [comment]
ahh too late. nevermind

**Comment by gkarolyi** [comment]
You're absolutely right, that was left in there accidentally - I had to delete it from my local state so I wouldn't get Pundit errors :)

**Comment by gkarolyi** [comment]
But your commit will override these changes, as soon as I can figure out how to resolve the conflict...

**Pull request merged**
